#!/usr/bin/env bash

# Usage:
# ./sbt <cmd>

CMD="$1"

if [ -z "$CMD" ]; then
  echo "Error: missing sbt command"
  exit 1
fi

# run sbt with the supplied arg
sbt -J-Xmx5120m \
    -J-XX:ReservedCodeCacheSize=1024m \
    -J-XX:MaxMetaspaceSize=1024m \
    -Ddotty.drone.mem=5120m \
    -Dsbt.ivy.home=/var/cache/drone/ivy2 \
    "$CMD"
